### ISSUE TITLE
Aucun tir

### ISSUE THREAD

**Issue by StarrBaits** [MauriceChocoSwiss/FCUWOLVERINE#2]
Bonjour / Bonsoir

Premièrement,  votre projet est absolument dingue ! 💯 

J'aimerais vous faire part du problème que je rencontre :

Le fcu fonctionne pas sur mon wolverine inferno gen2. (Monté sur une M4)

-la queue de détente est toujours détectée par l'arduino (high)
-j'ai pu modifier temporairement votre code et les billes se décomptes bien désormais, mais le solénoïde ne fonctionne pas pour autant (eeprom configuré)

Si ça vous dérange pas pour plus de simplicité de communication voici mon mail : kiliandauphingmx@gmail.com 

Merci de votre aide, car j'arrive malheureusement pas à le faire fonctionner.
👍

**Comment by MauriceChocoSwiss** [comment]
Salut, 
Merci pour ton retour :) 
T'es le premiers a me donner un retour même si je sais que plusieurs personnes utilisent déjà mon projet ^^ (croisé un mec en OP qui m'a dit "t'as vu le FCU que j'ai bariqué? Oui oui c'est le miens :D ) 

Bref, pour ton soucis de tir, j'ai eu le problème sur mon Reaper (mais pas sur mon Inferno G2). 
En fait j'ai mis un LDo pour baisser la tension mais ça ne marche pas de cette manière. Du coup si t'utilise uniquement une 2S j'ai modifier la carte (pas encore commit ici) pour que la batterie soit en directe sur l'inferno et le mosfet controle juste la masse du soleinoid. 

Pour ton probleme de détection de la trigger c'est chelou :/ Elle sort d'ou la carte que tu as ? Tu as fait tes essais sur une dev board ?

Et parlons ici, ça laissera une trace pour d'autres !

**Comment by StarrBaits** [comment]
![20220123_145459](https://user-images.githubusercontent.com/98241346/150681916-94c2cc81-240f-4f2d-bd54-75e6eb523ec0.jpg)

Salut, sur ma M4 j'ai ce FCU (voir photo ci dessus). J'ai acheté un kit prévu pour à la base une M249 "inferno gen 2 premium M249", mais j'ai dû racheter une trigger board plus le câblage pour pouvoir le monter sur une M4. (la partie solénoïde + Mécanique est plug and play pout une M4)).

Cependant le FCU que je possède actuellement reste bien celui d'une M249 (le FCU fonctionne parfaitement sur ma M4 actuellement).
J'ai acheté le PCB sur jlcpcb à partir du fichier gerber de ton projet. La carte arduino vient d'aliexpress. La trigger board vient de wolverine.

J'ai refais des test ce matin, voici les résultats :
- Avec un programme pour forcer la pin 8 (solénoïde), j'obtiens 4.46V dans le solénoïde (alimentation : batterie 2S)

- j'ai testé la continuité des fils de la prise wolverine, le fil marron est relié à la queue de détente, le fil rouge au selecteur. C'est inversé par rapport au schéma du fichier PDF
- j'ai testé la continuité sur un pcb nu, la borne 2 (selon le fichier PDF) de la prise wolverine est reliée à la résistance R1, la borne 3 est reliée à la résistance R2. C'est inversé par rapport au fichier PDF mais ça semble cohérent par rapport au test juste au dessus

- concernant le problème de queue de détente toujours activé, il restait du flux entre 2 pins de la prise wolverine, ça shuntait le contacteur de queue de détente

**Comment by MauriceChocoSwiss** [comment]
Ok je vois, c'est les FCU de base de Wolverine avec le Spartan.

Du coup j'ai refais la carte aujourd'hui, c'est couillon... Surtout qu'il m'en restait des ancienne version.

Alors pour la tension, c'est le pourquoi j'ai viré le regulateur de tension et que j'ai branché la batterie directement sur le plus du solenoid. Tu le verras sur le nouveau schéma. J'ai pas de photo a dispo par contre, le mien est collé ^^

C'est étrange car sur mes deux FCU j'ai deux trigger bord V2 et aucun soucis. Perso chez moi le fil marron c'est bien la gachette et le rouge le selecteur, le PDF n'est pas bon a ce niveau là, j'avais fait une erreur apparement

Pour les resistances c'est pa important, c'est des pull down, et R1 etR2 = 1K donc aucune incidence sur le fonctionnement.

A cool, effectivement si tu les mets en cour-circuit ca tir tout le temps ^^ 

Si tu te sens de faire de la modif je peux t'expliquer quoi faire mais faut être très précis sur la soudure. Il faut relier le pole 5 de la prise wolverine sur le + de la batterie, ainsi ça marchera. Sinon tu attends un peu et je posterai dans la semaine le nouveau PCB. Il arrivera déjà soudé avec les résistance, y aura plus qu'a souder deux trois truc genre le switch, le buzzer et les header pour les prises de la poignée de chargement et le bouton du chargeur. Ca devrai pas être trop chère, autant vu que je vais en commander 5 (minimum chez eux) je t'en envoi par la poste dans la foulé, soudé même si tu veux ;)

je suis aussi en ce moment en train de revoir le code pour le rendre plus réactif, car je trouves que ca manque un peu. J'avais pas trop la motiv mais si y a qq'un d'autre qui l'utilise je vais bien etre obligé ^^

**Comment by StarrBaits** [comment]
Super merci de tes conseils !

Du coup bonne nouvelle ! Le FCU fonctionne enfin avec mon wolverine (la défaillance venait bien de la prise wolverine qui était shuntée au niveau des câbles de la trigger....)

Ensuite concernant le PCB si tu en commande oui ça m'intéresse, je peux également en échange t'envoyer des composants (il me reste tout les composants sauf arduino, écran, buzzer)

Un ami regarde actuellement le code pour augmenter la cadence de tir en full notamment, car clairement le full est très creux comparé au FCU d'origine, (le full ne me sert que pour du tir sur cible ou pour un highlander XD)

Pour info je suis du 02 (Saint Quentin), si jamais on est peut-être pas loin l'un de l'autre pour les échanges.

**Comment by MauriceChocoSwiss** [comment]
De rien, c'est une bonne nouvelle en effet.
La cadence de tire depends de ton rof, mais effectivement je trouves aussi que ça manque un peu. Je pensais virer le contrôle de tension de la batterie pour le faire tous les x secondes.
Oubliez pas tous les deux qu'on est en 8hz, les fcu d'origine on sûrement des processeurs plus costaud en 16mhz voir plus. Si vous trouvez comment faire hésitez pas à partager le code 😉 si vous savez pas comment faire sur githib, je vous expliquerai 😉

Alors on est proche oui et non, le numero de nos départements est très proche mais je suis très loin en vrai, jsuis dans le 05 😂
Et pour les composants pas la peine, je vais les faire souder sur place, c'est des CMS, comme ça la carte est plus petite 😉


Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by StarrBaits** [comment]
Oui effectivement proche par le numéro XD.

Le nouveau pcb avec composants en cms m'intéresse énormément de part la petite taille des composants et donc logiquement fcu plus petit 😀

Oui même rof au max et en faisant varier le dwell le full à très peu de cadence (on dirait la cadence d'une réplique bas de gamme avec une batterie nimh rincée lol)

Voilà ce qu'on a testé pour modifier la cadence :
Si nous avons bien compris, dans les fichiers "SelectorOnFull.cpp" et "SelectorOnBurst.cpp", la variable "rof" défini le délai où le solénoïde est à l'état 0. Ainsi un rof de 30 ne correspond pas à une cadence de tir de 30 bb/sec.
Pour calculer la cadence théorique, j'ai calculé le temps de cycle de la réplique :
temps d'ouverture de la solénoïde (dwel) = dwel/2.5
temps de fermeture de la solénoïde (rof) = 1000/rof
temps de cycle = dwel/2.5 + 1000/rof
cadence théorique = 1000/"temps de cycle"

Par exemple, pour un dwel de 70 et un rof de 30 je calcule une cadence théorique d'environ 16bb/sec.
J'ai donc modifié la valeur max du dwel dans le code pour correspondre à la cadence voulue. Pour les tests, je choisis la valeur du rof d'après un calcul sur excel pour ne pas trop modifier le code pour l'instant.
Avec ces nouvelles valeurs, j'obtenais une meilleure cadence. Je pense que ça nécessite encore des ajustements car étant novice sur arduino, je ne sais pas trop où il peut y avoir du délai dans la void loop qui pourrait réduire la cadence.

Que penses-tu de mes calculs ? (je pourrais ajouter le fichier excel si besoin)

Ensuite j'ai codé quelques lignes pour par exemple allumer la led lors de l'appui sur joystick etc....

Je me ferai plaisir de partager les modifications de code si on arrive à un résultat satisfaisant !

**Comment by MauriceChocoSwiss** [comment]
C’est étrange car perso ça va pas mal pour mon utilisation (c’est vrai que j’ai pas cherché les 16bb/sec mais les 750c/m de la G36 soit 12bb/sec ^^) 

Alors ces fichiers la vont disparaitres, je vais faire un seul fichier de tir, je te laisserai poster tes modifs, que j'ajouterai dans le code, même par exemple la led qui s'allume à l'appuie du bouton (ca m'a toujours fait chier mais j'y ai jamais pensé ^^)

La variable ROF définit le temps d'attente avant de passer au tir suivant à la suite plutot, le temps de fermeture du solénoïde n'est pas maitrisable, c'est intrinsèque. Et le dwel, comme tu l'a compris, le temps que va passer le solenoide en position ouvert. 

A la base c'était bien en bb/Sec mais c'est vrai que dans mon calcul j'ai oublié le dwel ^^ Du coup 30, c'était sensé être 30bb/sec ^^ Du coup effectivement avec ton calcul on arrive qu'a la moitié ^^ Je vais voir pour faire une division dynamique alors, ainsi si on change le dwel, ca changera le rof, et il faudra changer le rof pour revenir a ce que l'on veut comme valeur ;) Je vais trouver une formule pour ca, ou alors tu as déjà ton idée, j'avoue que j'ai pas trop le temps, j'ai pleins d'autres dev a coté et pas de temps pour l'arduino.

Pour ce qui est des latences, il n'y a pas d'autres délais que celui la lors du tir. Il reste deux choses consommatrices de temps, l'écran et le calcul de tension. C'est lui qui mange le plus de "ressources", j'avais fais comme ça à l'époque et ça m'aller bien pour mon G36 mais je le trouve mou aussi, j'avais pas envie de prendre du temps et j'ai surtout passé un très long moment a chercher pourquoi le solénoïde marchait pas, avec retour en garantie etc... (1 an et demi :D) mais après avoir trouvé j'ai trouvé que c'était mou aussi par moment et j'ai capté que c'était le voltage. Ca fait seulement 15 jours que je me suis repenché sur la G36, j'ai peu de temps pour ca et je suis plus trop dans le moderne maintenant mais plus le ww2 ^^ et mon reaper ne marche qu'en semi alors je m'en fichais :D 

hésite pas à créer ta branche pour poster tes essais sans risques et puis quand le moment sera venu, on intégrera tes modifs si tu veux ;) Il y a plein de tuto sur le net, mais en gros, tu clique sur fork en haut a droit dans la page git du projet, ça va créer ta branche, tu peux faire tes modifs dessus et les commiter (envoyer) et quand ce seras bon on feras une pull request ;)

**Comment by MauriceChocoSwiss** [comment]
Yop, petite question, tu peux me mesurer la résistance du solénoïde et me donner sa ref, il me semble qu'elle commence par BV214A etc... Les miens sont pas accessibles facilement. Si t'arrive a faire une photo clair des infos notées dessus ca serait encore mieux !

**Comment by StarrBaits** [comment]
Salut,

Mesurer la résistance c'est faisable à partir du câblage qui se connecte au FCU, je peux le faire ce soir.
Mais concernant les inscriptions sur le solénoïde j'ai essayé de regarder sur le net mais aucune photo intéressante....
Et clairement je veux pas démonter mon système car j'ai pris un temps fou pour l'alignement le calage, le reglage aux ptits oignons etc.... et pour accéder au solénoïde obligé d'ouvrir ma GB et donc tout dérégler....

Pour le code on regarde ce soir de notre côté voir si on arrive à améliorer la cadence.
On se tiens informé des résultats obtenus (négatif ou positif)

**Comment by MauriceChocoSwiss** [comment]
Ok la résistance ce sera déjà pas mal, je pensais que ton système n'était pas encore monté c'est pour ça que je t'ai demandé, effectivement ne va pas démonter si comme moi tout est calée 😉
A plus tard

**Comment by StarrBaits** [comment]
J'ai mesuré la résistance du solénoïde, je trouve 6.7ohm. ça me parait cohérent, qu'en penses-tu ?

J'ai créé ma branche avec la modification des LED et avec la cadence modifiée.
Il a fallu seulement 3 lignes pour soulager l'arduino et obtenir une cadence qui correspond aux valeurs. J'étais trop content quand j'ai vu que ça marchait.
Pour faire ça je refais un test de trigger avant les tests de joystick. Si la trigger est encore activée, ça renvoie vers la première ligne de la void loop. Je pense que ça n'affecte pas le delay en mode sniper mais je n'ai pas essayé.

N'hésite pas à poser des questions sur les modifications ou à modifier la façon que j'ai codé car ma façon de coder est assez "barbare" 😆

**Comment by MauriceChocoSwiss** [comment]
Merci pour la valeur, oui elle semble cohérente mais du coup je vais galérer a trouver le bon mosfet du coup ^^

Yes pas de soucis pour le code, je regarderai ce que t'as fais, si ca ce trouve ton approche est bonne ;) (esquiver les contrôle de joystick si la gâchette est pas appuyé c'est un bon plan, j'y avais pas pensé mais ca évite des IF ;)

**Comment by MauriceChocoSwiss** [comment]
Tien voici un apercu ;) 

![image](https://user-images.githubusercontent.com/23436049/150850654-652b75a9-af95-483a-ad5d-57f847e609e5.png)

![image](https://user-images.githubusercontent.com/23436049/150850690-082af795-836d-493a-906d-c59f60372d30.png)

La carte arriveras avec les composants CMS soudés, il resteras a mettre le joystick, l’Arduino, la led et si jamais le buzzer en déporté (je l'ai viré de la carte pour gagner de la place)

**Comment by StarrBaits** [comment]
Super top ! Niveau dimensions du PCB ça donne quoi environ ? 
En plus ce qui reste à souder c'est simple :)

Le buzzer j'en est également pas besoin

**Comment by MauriceChocoSwiss** [comment]
J'ai check tes modifs, c'est cool, je connaissais pas le goto ;) 

Par contre du coup plutot que d'avoir un simple flash tu laisse la led allumé, perso j’suis pas fan car quand tu va faire du bâtiment la nuit, ca va éclairer fort ^^ mais c'est pas un soucis, ca peut rester ainsi sur ta branche si tu veux pour ton utilisation :) 

Je te laisse faire tes tests, quand tu auras fini on feras une pull request avec tes modifs de la led pour faire simple et tu supprimer ta branche, ensuite, tu pourras en refaire une après la PR (normalement y a une autre méthode mais c'est long a expliquer ^^)  et moi je remettrai les parametres de la led comme je les aiment :D 

Dimension 20.5mm de large et 60.3mm de long

**Comment by StarrBaits** [comment]
Effectivement les dimensions sont réduites c'est top !

Concernant la led allumée tu parles pour l'alarme de bille ? Si oui moi ça ne me gêne pas au contraire car le FCU va être intégré dans un support modelisé et imprimé en 3d sur mesure et il est prévu que la led soit dans un "fourreau" très fin qui laissera passer la lumière que très peu;)  (en gros c'est le même principe qu'un abat-jour sur une lampe de chevet)

Concernant le code on a encore des tests et choses à essayer donc on se dit quoi pour l'avancement.

**Comment by MauriceChocoSwiss** [comment]
Ok je vois, l'idée est bonne, c'est le principe de l'open source chacun le customize a sa sauce ;)

**Comment by StarrBaits** [comment]
Exactement la synergie est top sur ce genre de projet open source 😁

Si je peux t'aider concernant la création d'un boitier 3d ou autre pour adapter le FCU à ta réplique je peux t'aider 😉

**Comment by MauriceChocoSwiss** [comment]
c'est gentil mais j'ai déjà fait le miens y a un moment ^^ et pour mon g43 pas besoinc'est dans la crosse, en mode light sans buzzer, led etc... Tiens moi vite au courant pour tes modifs, moi je pars en voyage donc le PCB ce sera pour Mars surement, de toute facon avec 3 semaines de livraison ^^

**Comment by StarrBaits** [comment]
Dac, concernant les modifications du code on va normalement plus rien changer, mis à part essayé de faire un  code pour éteindre l'écran au bout de 30 secondes d'inutilisation par exemple et le rallumer avec un appui long sur le joystick

**Comment by MauriceChocoSwiss** [comment]
je suis pas sur que sur c'est écran tu aies un mode OFF mais tu peux vider l'affichage ca oui ;)

**Comment by StarrBaits** [comment]
Merci de l'info, on essaye ce soir de trouver comment faire ça afin d'optimiser un max les ressources pour le tir

**Comment by MauriceChocoSwiss** [comment]
ben après si tu le mets dans un IF qui regarde si tu l'as déjà fait, il passe une fois et basta, il y reviendra plus sauf si tu déverrouille par exemple ;)

**Comment by MauriceChocoSwiss** [comment]
J'ai checké le code pour faire la pull request et j'ai vu qu'il  va y avoir un petit couaq je pense. Quand la led de chargeur presque vide est allumé et que la led de charegeur vide va s'allumer tu auras les deux en même temps. Physiquement pas de soucis, mais tu auras les deux ^^ Je vais faire une pull request de ton code, tu pourras ajouter ta modif avec le screen et moi je peux annoter ton code pour que tu puisse corriger deux bricoles ;) et moi je pourrais intégrer uniquement les modifs de perfo sans celle du fonctionnement de la LED. j'ajouterai tes modifs dans une nouvelle branche pour ceux qui veulent la led en fix ;)

Pour te servir de la nouvelle branche faudra faire un fork de celle ci ;) j'ai pas encore mis a jour mon master avec mes modifs. Après j'y mettrai les tiennes ;)

**Comment by StarrBaits** [comment]
Dac, oui effectivement la led de fin de bille donne une couleur rose dû à un double allumage.

Si j'ai le temps ce soir on corrige le code suite à tes annotations, merci du check :)

**Comment by StarrBaits** [comment]
Salut,

On a essayé quelques bricole sur le code mais rien n'a fonctionné mieux qu'avant. Cependant j'ai par moment comme des "ratés" au niveau du déclenchement du solénoïde, je mets fortement en soupçon la tension d'alimentation du solenoide qui doit être juste limite, ce qui engendrait ces quelques ratés par moments...

J'attends ton retour sur le prochain PCB pour voir si l'alimentation sera meilleur du à l'alimentation en "direct"  du solenoide sur la batterie.✌

**Comment by StarrBaits** [comment]
On a également essayé d'optimiser la réactivité alors le gros mangeur de ressource est bien le calcul de tension (l'écran est négligeable en consommation). En désactivant le calcul de tension on passe de 300 millisecondes à 50 millisecondes de temps de réaction, ce qui fait une sacrée différence.

On a donc essayé de mettre un interval de calcul de la tension (par exemple le calcul s'effectue toutes les 30 secondes) mais le problème c'est soit ça calcul tout le temps ou soit ça calcul jamais. (on pense qu'il faudrait faire un autre calcul de la tension pour pouvoir intégrer un interval de calcul)
On arrive pas à trouver la solution depuis 2 soirées dessus....

**Comment by MauriceChocoSwiss** [comment]
Yop, 
alors pour les ratés c'est ce que je t'ai expliqué, comme actuellement ca passe par un LDO, tu n'a que ~5V mais c'est pas assez pour le soleinoide (6V mini) du coup j'ai fait un pont et ca marche mieux (attention faut couper la piste sur le circuit sinon tu vas faire un retour dans l'arduino sur +5V en balançant les 7V de la lipo et ca, il va pas kiffer ^^ Du coup c'est sur les nouveaux PCB seront mieux :D

Comme attendu c'est le calcul de la tension qui fait chier, j'avais pas pris le temps de faire les mesures, comme je suis sur de mon coup, j'ai directement mis un timer sur le calcul. Il faut faire une fonction non bloquante, je l'ai déjà faite, donc si tu veux pas te casser la tête tu l'auras avec la maj de mon code ;) Et oui les timer c'est un peu chiant ^^

**Comment by StarrBaits** [comment]
Oui c'est exactement ce que tu me disais, je vais donc attendre ton nouveau PCB et pas m'embêter à faire un pont.

On a peut-être trouvé une solution pour le calcul de tension on essaye ça demain. 
Nickel si tu as déjà une astuce !

Au cas où le pont tu le fais entre qui et qui ?(peut-être j'aurais le courage de le faire demain XD)

**Comment by MauriceChocoSwiss** [comment]
Dur a expliquer comme ca, j'ai fait un screen< en rouge la ou couper la piste et en blanc le fil a ajouter, en coupant la piste faut t'assurer que le + ne touche pas le - sinon court circuit...
![Capture d’écran 2022-01-27 231404](https://user-images.githubusercontent.com/23436049/151452967-5b015bb5-a6a2-49a3-b5d6-26e5aec7de5d.png)

**Comment by MauriceChocoSwiss** [comment]
Et pense a commit tes mises a jour, même si tu rechange après, ca laisse une trace et je peux regarder :D

**Comment by StarrBaits** [comment]
Merci pour l'info, oui on va mettre la mise à jour ce soir si il y a du changement

**Comment by MauriceChocoSwiss** [comment]
Yop, tiens moi au courant si c'est bon ou pas, hésite pas a commit ce que t'as fait, autant je suis passé a coté d'un truc moi aussi ;)

Si tu peux le faire en début de soirée j'ai du temps pour ça ce soir

**Comment by StarrBaits** [comment]
Oui normalement ça sera fait cette aprèm :)

**Comment by MauriceChocoSwiss** [comment]
Nice, merci 😉

**Comment by StarrBaits** [comment]
Au final, rien à optimiser, la latence venait du délai qui fait clignoter la LED de batterie faible 😂. Donc ce n'est pas gênant en jeu. J'ai modifié le code d'après tes remarques dans le pull request.

**Comment by MauriceChocoSwiss** [comment]
Yes j'ai tout reçu, je fais en sorte d'intégrer nos changement respectifs et tu pourras  forker la branche avec les leds fix

**Comment by MauriceChocoSwiss** [comment]
Voilà, les modifs sont faites, tu auras sur la branche withLedFix le code à jour avec nos modifs respectives et les leds fixes ;) Sur la master j'ai laissé sans les leds fixes ;)

Tu peux forker la nouvelle branche et supprimer l'ancienne que tu avais ;)

j'attends ton retour pour savoir si tout marche correctement

**Comment by StarrBaits** [comment]
![Screen Shot 2022-01-29 11h10min19sec](https://user-images.githubusercontent.com/98241346/151656981-02915004-2865-4d69-9f30-0a6f46788541.PNG)

Salut, j'ai un petit souci quand je compile ton code. Est-ce que tu sais ça peut venir d'où ?
Voici les messages d'erreurs :

D:\Téléchargement\FCUWOLVERINE-WithFixLed\FCU-Wolverine origine\FCU-Wolverine\FCU-Wolverine.ino: In function 'void loop()':

FCU-Wolverine:347:40: error: no matching function for call to 'VoltageCtrl::alarmVoltage(int8_t&)'

In file included from D:\Téléchargement\FCUWOLVERINE-WithFixLed\FCU-Wolverine origine\FCU-Wolverine\FCU-Wolverine.ino:3:0:

D:\Téléchargement\FCUWOLVERINE-WithFixLed\FCU-Wolverine origine\FCU-Wolverine\VoltageCtrl.h:12:8: note: candidate: bool VoltageCtrl::alarmVoltage(int8_t, long unsigned int)

D:\Téléchargement\FCUWOLVERINE-WithFixLed\FCU-Wolverine origine\FCU-Wolverine\VoltageCtrl.h:12:8: note:   candidate expects 2 arguments, 1 provided

D:\Téléchargement\FCUWOLVERINE-WithFixLed\FCU-Wolverine origine\FCU-Wolverine\FCU-Wolverine.ino:561:61: warning: overflow in implicit constant conversion [-Woverflow]

exit status 1

no matching function for call to 'VoltageCtrl::alarmVoltage(int8_t&)'

**Comment by MauriceChocoSwiss** [comment]
Ah chiotte, je vais regarder ! j'étais persuadé ce matin que ca passé (mais bon a 2h du mat et quelques grammes d'alcool, je suis pas sur ^^) Je regarde et je te dis quoi ;)

**Comment by MauriceChocoSwiss** [comment]
C'est bon c'est corrigé ! Test bien les menus, surtout l'enregistrement des paramètres, comme j'ai pas mal modifié cette partie pour alléger le code autant ca marche plus

**Comment by StarrBaits** [comment]
Merci ça "fonctionne", par contre je crois qu'il vaut mieux coder à jeun 😆. Maintenant c'est impossible de changer les valeurs d'eeprom dans les sous menus. Et la partie "joyPushed" ne marchait plus, j'ai du passer de analogread à digitalread et modifier la condition du if.
Cependant la réactivité du joystick dans les menus est bien meilleure

**Comment by MauriceChocoSwiss** [comment]
Alors ca c'est étrange pour le analogue read, parce que le push du joystick est sur une entrée analogique, surtout que c'est comme ca depuis le début quoi ^^ 🤔 Enfin je crois que je sais d’où ça vient la aussi. Mais c'est tant mieux si ca marche avec un digitalRead ;)
Pour l'eeprom j'avais justement besoin que tu tests, mes FCU ne me sont pas accessible et j'ai codé a l'aveugle. Je penses savoir d'ou vient le soucis, je testerai demain dans l'aprem si j'ai le temps ;)

**Comment by MauriceChocoSwiss** [comment]
Salut, je reviens pour t'apporter des news, j'ai mis à jour le code, C'était pas long mais j'avais pas le temps pour ce projet. J'ai tester et tout semble bon, la cadence est en effet bien meilleur ! Je te laisse faire des tests de ton coté aussi si tu peux ;) 

J'ai recu les nouveaux PCB mais je suis pas encore rentré chez moi. Je te donnerai des news ;)

**Comment by StarrBaits** [comment]
Salut, merci de ton retour malheureusement je peux pas tester le code car j'ai cramé mon arduino... Tiens moi informé pour tes nouveaux PCB, je t'en achète un tu me l'envoie si tes ok et je pourrais tester à nouveau avec un nouveau arduino.

**Comment by MauriceChocoSwiss** [comment]
Yop, yes j'en ai monté un ce week-end mais je suis parti en dép, j'ai pas pu tester, les cartes sont justes soudées avec les composants cms, reste à mettre les headers ou non, moi je les ai mis sur ma carte de test mais je les virerai après.

Je te tiens au jus 😉

**Comment by MauriceChocoSwiss** [comment]
Yop, bon j'ai testé et ca marche nickel, il a fallu modifier quelques input pour les entrée, je pense que le V1 n'était pas cablé comme sur le schéma... Bref, du coup tout fonctionne, le PCB est bien plus petit et ca c'est top !

Si tu veux m'envoyer ton adresse etc je te laisse m'envoyer un mail ici: thechocoswiss@gmail.com

A plus ;)

**Comment by StarrBaits** [comment]
Salut Choco, super content que ça fonctionne correctement. Hâte de pouvoir essayer également :) . Je te contact par mail pour mes coordonnées. Merciiii de ton retour encore .
