### ISSUE TITLE
Trying to get board made but issues with bom and csv file...

### ISSUE THREAD

**Issue by Billybob32341** [MauriceChocoSwiss/FCUWOLVERINE#4]
Hey Maurice, trying to get the FCU made but having issues trying to get the board made and assembled using the BOM and CSV provided..., any chance you could point me in the right direction for what website is best using your files to get them made, thanks

**Comment by MauriceChocoSwiss** [comment]
Hi, intresting, it's the bom and gerber file i used to make it. I use lcsc factory service to build it.
I'll test it to check if both files work with lcsc.
But for sûre, you can't get all parts mounted directly as i used standard part to represent some other how as wired and not directly mounted on, like buzzer and other optional things.

Did you know how this files works ? And how to solder some components on pcb ?

**Comment by Billybob32341** [comment]
Ill have to give it a shot with LCSC then maybe it's just the website giving me problems, ill let you know, and yup i've taken a look at the schematics, I may have to make some modifications on the wiring harness for the polarstar etc, but same principle as the wolverine, single solenoid running 5v+ the wolverine is pretty much identical to the jack I'm trying to get running... smashed the screen and figure this is cheaper then a new FCU and more versatile, and yup I use to make pcbs by etching back when I was kid, so soldering and putting the components on the board isn't too big a deal if their not micro resistors etc lol

**Comment by MauriceChocoSwiss** [comment]
Humm ok, i don't know if you can modify the pcb directlly from a gerber 🤔 But if you be sure of what you do ^^ Arduino and lipo can make some magical things 🤣🤣🤣🤣
I don't know if polarstar and Wolvy use the same plug (the more difficult to find) and wirring or not. 

Actually, with the gerber and bom, LCSC can solder all resistors, the little transistor, but not the big diode (at the moment i build my own pcb, they can't, I don't know now), this one and other components, you have to solder it yourself.

**Comment by Billybob32341** [comment]
It all comes down to 3 things i think lol, trigger ,solenoid ,selector, so no need to modify anything really, just find out what connections are what on the 5 plug wiring harness for the wolfy which I know what they are on the p*, cut mine in half, and wire the wolfy harness to mine knowing the trigger wire, solenoid wires, and selector wires, 5 wires on both the p* and wolfy... 

So then do you order the board separate the parts separate and build them from their because I still can't seem to find where I can even get them semi assembled as I would rather have lcsc solder all the resistors the transistor etc i can deal with the nano and diodes etc... If you do even sell them or want to go in on a joint venture to get them working for p*s as well... I'd be interested in that as well... just trying to get my hpa up and going again

**Comment by MauriceChocoSwiss** [comment]
Yes of course you can go this way ^^ Simple, reliable ^^

Yes, I order some parts separatly like Arduino, screen, headers for options like buzzer or mag switch and the diode that lcsc can't solder. I've updated the main project page with links for screen and multiway switch. 
I don't sell anything sorry... Ans sorry it's jlcpcb, a co-company of lcsc. The diode is big enought (for me the resistors too) to be soldered, have you got a friend how can help you ?

**Comment by Billybob32341** [comment]
Pretty much haha I figure they are basically the same mechanically , so for the $30 cad it's worth an experiment... Sounds good I can do that as well that's no issues I've priced it out ordering all the parts and the pcbs separate , could I get the CPL file if you have it tho ? With like just the things JLCPCB will solder..., so like a BOM with just the resistors, transistor etc, and the CPL file for that BOM, so I can go through ordering the pcb with the resistors and transistor pre-soldered then just have to finish the rest I guess they are offering a free assembly promo right now so might as well take advantage of it...

**Comment by MauriceChocoSwiss** [comment]
Yop, yes you could experiment ^^

I've looked for CPL file and i'll add it to the repo soon. Last time I've print the PCB i don't remember they ask it ^^ Just select bottom side in the PCB assembly option.

**Comment by Billybob32341** [comment]
Awesome can finally order the boards thanks for the help ! Now just to figure out how to make it work with the p* jack lol and my build,,,, any chance you have the pinout for the wolfy as well, make things a little easier to get the jack working, I'm going to try to eliminate the trigger board all together, by just using my own micro switch for both the trigger and selector,

**Comment by MauriceChocoSwiss** [comment]
Ah sounds good ! Yes, 2 wires for the solenoid, 1 for selector and 1 for the trigger. It's a common + on wolfverine bord. You need to test on the p* one to be sure 😉
I dont have the wirring diagram for the wolfverine bord, but with my drawing, you can know how to wire 😉 if you need help, make a schema and post it heure to check 😊

**Comment by Billybob32341** [comment]
Sounds good, I've looked around and someone mentioned on another forum brown is +, blue trigger,red selector,black is first solenoid and white is second, so far I've patched into my harness on brown and blue and got a trigger working on a custom hpa build with a small micro switch, so the info seems legit, I think Ill be able to handle it from here I hope lol if I have anymore concerns ill put something put again, thanks for all the help though man, and once again your a hero to the community haha

**Comment by MauriceChocoSwiss** [comment]
Good to know ;) 

Your welcome Bro ;)
